name: Zowe CLI CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    env:
      OS: ${{ matrix.os }}
      NODE: ${{ matrix.node-version }}
      NODE_OPTIONS: --max_old_space_size=4096

    if: (github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository) && !contains(github.event.head_commit.message, '[ci skip]')

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use NPM v7
      id: npm7
      run: npm install -g npm@^7

    - name: Make executable
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: chmod 777 license.sh

    - name: List
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: ls -la

    - name: List
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      run: cat license.sh

    - name: Install Node Package Dependencies
      id: install
      run: npm install

    - name: Build Source
      id: build
      run: npm run build

    - name: Test
      id: test
      run: npm run test --workspaces